logging:
  level:
    root: WARN
    com:
      home:
        employeemanagement: DEBUG
    org:
      springframework: INFO
  file:
    name: app.log

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    properties:
      javax:
        persistence:
          validation:
            mode: none
  boot:
    admin:
      client:
        url: http://localhost:9080
        instance:
          metadata:
            tags:
              environment: dev
            user:
              name: rahul
              password: password

  datasource:
    url: jdbc:mysql://localhost:3306/employee_management?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: employeeManager
    password: Password123

server:
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  greeting: Welcome To EmployManagement!!
  tags:
    environment: dev
